= Not Alone

NOT ALONE est un jeu asymétrique opposant un joueur (la Créature) aux autres joueurs (les Naufragés).

Si vous incarnez l’un des Naufragés, vous explorerez Artemia au moyen de cartes Lieux. Aidés de vos cartes Survie, vous tenterez de résister à la traque de la Créature jusqu’à l’arrivée des secours.



Si vous incarnez La Créature, vous traquerez les Naufragés de l’espace afin de les assimiler à la biomasse de la planète. Aidée de vos cartes Traque et des manifestations d’Artemia, vos assauts répétés annihileront progressivement la volonté des Naufragés, ce qui les liera inéluctablement à la planète.


== Description

25e siècle, l’Humanité s’est envolée depuis longtemps vers les étoiles. Elle a voyagé aux
confins de la galaxie et pourtant, elle n’a jamais rencontré d’autres formes de vie intelligente.
En fouillant les archives centrales de la vieille Terre, vous avez découvert qu’une planète
du nom d’Artemia avait été rayée des cartes officielles et qu’aucune autre donnée n’était
disponible. Intrigués, vous montez une expédition.
Les premiers relevés de la surface d’Artemia révèlent une planète de classe M, accueillante
pour l’homme et abritant une faune et une flore riches et variées. Lors de votre entrée
dans l’atmosphère, un puissant champ magnétique met les ordinateurs de bord hors
service. Après avoir lancé un SOS, le capitaine ordonne l’évacuation du vaisseau avant
l’inévitable crash.
Sains et saufs, vous entamez l’exploration des environs lorsque vous entendez les cris
d’agonie de votre capitaine. Au loin, vous distinguez une silhouette qui vous observe.
Vous n’êtes pas seul...

== Project Layout

The current source code organization is based on the following article:

https://frakton.com/utilizing-maven-front-end-plugin-for-angular-spring-boot/

== Livrables attendus

=== Analyse du domaine

Objectif::
Description du jeu _Not Alone_ sous la forme d'un diagramme de classes conceptuelles et d'actions

Moyens::
Utilisez une approche itérative pour découvrir toutes les classes conceptuelles et les actions du jeu.

=== Conception préliminaire

Objectif::
Découpage de la solution en composants (ou sous-systèmes) et spécification des interfaces fournies et requises par ces composants

Moyens::
Utilisez des diagrammes d'interaction (séquence, communication) pour décrire l'échange de messages entre les composants pour en déduire leurs interfaces.

=== Conception détaillé

Objectif::
Spécification détaillée des composants: leur structure (diagramme de classes de conception), ainsi que le comportement de chaque opération fournie par le composants. Le comportement peut-être décrit en utilisant les diagrammes d'activité, d'interaction, les machines d'état, ainsi que OCL.

Moyens::
Appliquez les concepts vus en cours: design patterns, principes GRASP, bonnes pratiques, etc. 

=== Code source

Objectif::
Code de mise en oeuvre et tests de l'application.

Moyens::
Appliquez les enseignements de l'UE "Construction et évolution de logiciels" pour produire un code source de qualité.