/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IGamePhase {
    GamePhase?: number;
}
export interface IGamePhaseArgs {
    GamePhase?: number;
}
export const GamePhaseCodec: thrift.IStructCodec<IGamePhaseArgs, IGamePhase> = {
    encode(args: IGamePhaseArgs, output: thrift.TProtocol): void {
        const obj: any = {
            GamePhase: args.GamePhase
        };
        output.writeStructBegin("GamePhase");
        if (obj.GamePhase != null) {
            output.writeFieldBegin("GamePhase", thrift.TType.I32, 1);
            output.writeI32(obj.GamePhase);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IGamePhase {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_1: number = input.readI32();
                        _args.GamePhase = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            GamePhase: _args.GamePhase
        };
    }
};
export class GamePhase extends thrift.StructLike implements IGamePhase {
    public GamePhase?: number;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IGamePhaseArgs = {}) {
        super();
        if (args.GamePhase != null) {
            const value_2: number = args.GamePhase;
            this.GamePhase = value_2;
        }
    }
    public static read(input: thrift.TProtocol): GamePhase {
        return new GamePhase(GamePhaseCodec.decode(input));
    }
    public static write(args: IGamePhaseArgs, output: thrift.TProtocol): void {
        return GamePhaseCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return GamePhaseCodec.encode(this, output);
    }
}
