/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IJoinRequest {
    name?: string;
}
export interface IJoinRequestArgs {
    name?: string;
}
export const JoinRequestCodec: thrift.IStructCodec<IJoinRequestArgs, IJoinRequest> = {
    encode(args: IJoinRequestArgs, output: thrift.TProtocol): void {
        const obj: any = {
            name: args.name
        };
        output.writeStructBegin("JoinRequest");
        if (obj.name != null) {
            output.writeFieldBegin("name", thrift.TType.STRING, 1);
            output.writeString(obj.name);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IJoinRequest {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.name = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            name: _args.name
        };
    }
};
export class JoinRequest extends thrift.StructLike implements IJoinRequest {
    public name?: string;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IJoinRequestArgs = {}) {
        super();
        if (args.name != null) {
            const value_2: string = args.name;
            this.name = value_2;
        }
    }
    public static read(input: thrift.TProtocol): JoinRequest {
        return new JoinRequest(JoinRequestCodec.decode(input));
    }
    public static write(args: IJoinRequestArgs, output: thrift.TProtocol): void {
        return JoinRequestCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return JoinRequestCodec.encode(this, output);
    }
}
