/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IResponse {
    value?: boolean;
    detal?: string;
}
export interface IResponseArgs {
    value?: boolean;
    detal?: string;
}
export const ResponseCodec: thrift.IStructCodec<IResponseArgs, IResponse> = {
    encode(args: IResponseArgs, output: thrift.TProtocol): void {
        const obj: any = {
            value: args.value,
            detal: args.detal
        };
        output.writeStructBegin("Response");
        if (obj.value != null) {
            output.writeFieldBegin("value", thrift.TType.BOOL, 1);
            output.writeBool(obj.value);
            output.writeFieldEnd();
        }
        if (obj.detal != null) {
            output.writeFieldBegin("detal", thrift.TType.STRING, 2);
            output.writeString(obj.detal);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IResponse {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.BOOL) {
                        const value_1: boolean = input.readBool();
                        _args.value = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.detal = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            value: _args.value,
            detal: _args.detal
        };
    }
};
export class Response extends thrift.StructLike implements IResponse {
    public value?: boolean;
    public detal?: string;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IResponseArgs = {}) {
        super();
        if (args.value != null) {
            const value_3: boolean = args.value;
            this.value = value_3;
        }
        if (args.detal != null) {
            const value_4: string = args.detal;
            this.detal = value_4;
        }
    }
    public static read(input: thrift.TProtocol): Response {
        return new Response(ResponseCodec.decode(input));
    }
    public static write(args: IResponseArgs, output: thrift.TProtocol): void {
        return ResponseCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return ResponseCodec.encode(this, output);
    }
}
