/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IWinner {
    winner?: string;
    message?: string;
}
export interface IWinnerArgs {
    winner?: string;
    message?: string;
}
export const WinnerCodec: thrift.IStructCodec<IWinnerArgs, IWinner> = {
    encode(args: IWinnerArgs, output: thrift.TProtocol): void {
        const obj: any = {
            winner: args.winner,
            message: args.message
        };
        output.writeStructBegin("Winner");
        if (obj.winner != null) {
            output.writeFieldBegin("winner", thrift.TType.STRING, 1);
            output.writeString(obj.winner);
            output.writeFieldEnd();
        }
        if (obj.message != null) {
            output.writeFieldBegin("message", thrift.TType.STRING, 2);
            output.writeString(obj.message);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IWinner {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.winner = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.message = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            winner: _args.winner,
            message: _args.message
        };
    }
};
export class Winner extends thrift.StructLike implements IWinner {
    public winner?: string;
    public message?: string;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IWinnerArgs = {}) {
        super();
        if (args.winner != null) {
            const value_3: string = args.winner;
            this.winner = value_3;
        }
        if (args.message != null) {
            const value_4: string = args.message;
            this.message = value_4;
        }
    }
    public static read(input: thrift.TProtocol): Winner {
        return new Winner(WinnerCodec.decode(input));
    }
    public static write(args: IWinnerArgs, output: thrift.TProtocol): void {
        return WinnerCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return WinnerCodec.encode(this, output);
    }
}
