export enum SurvieCard{
  RIPOSTE, VORTEX, ESQUIVE, VOLTE_FACE, ADRENALINE, ALERTE, AMPLIFICATEUR, BROUILLAGE, CAVALE,
  DETECTEUR, DRONE, ENTRAVE, EQUIPEMENT, FAUSSE_PISTE, HOLOGRAMME, LEURRE, MIMETISME, NAVETTE,
  PLANQUES, PORTAIL, RALLIMENT, REFUSE, REGENERATION, RESISTANCE, RETRAITE, SACRIFICE, SECOND_SOUFLE,
  SIXIEME_SENS, SYSTEME_D, TENACITE, VACCIN
}
