export enum TraqueCards{
  ACHARNEMENT, CHAMPS_DE_FORCE, FLASHBACK, MUTATION, ANGOISSE, ANTICIPATION, CATACLYSME, HURLEMENT,
  CLONE, DEPLOIEMENT, DESESPOIR, DETOUR, DOMINATION, EFFROI, EMPRISE, EPIDEMIE, FAILLE_TEMPORELLE,
  GARGANTUA, HARCELEMENTS, INTUITION, MAGNETISME, MIRAGE, PSYCHOSE, REMINISCENCE, REPERAGE,
  SABLES_MOUVANTS, SOIF_DE_SANG, STASE, TELEPATHIE, TORNADE, TOXINE, UBIQUITE, VIRUS, ZONE_INTERDITE,
  INERTIE, INTERFERENCES
}
