= Synthèse des règles

== Cartes lieu

Fonctionnement:: Chaque carte Lieu possède un n°, un nom et un pouvoir pouvant être activé par les Traqués.

Adjacence:: Deux cartes Lieu sont adjacentes si elles ont un bord en commun, horizontal ou vertical.

Lieux multiples:: Quand un jeton est placé sur 2 Lieux adjacents, le placer à cheval sur ces 2 Lieux.

Copier le pouvoir d'un Lieu:: Pour utiliser cet effet, un Traqué doit pouvoir utiliser le pouvoir de la carte Lieu qu’il a initialement jouée en Phase 1 :

- cet effet permet à ce Traqué d’utiliser un Lieu révélé sans jouer la carte associée, même si ce lieu est inutilisable ou inaccessible pour lui,

- tout jeton Traque sur le Lieu copié est sans effet sur ce Traqué.

Lieu inaccessible:: Un Lieu non révélé est inaccessible pour les Traqués.
Les jetons Traque peuvent être placés ou déplacés sur un Lieu inaccessible.

Lieu inutilisable:: Lorsqu'un Lieu est inutilisable, son pourovir peut être copié grâce au pouvoir d’une carte Lieu ou d’une carte Survie.

.Liste des cartes lieu
[cols="10,30,60",options="header"]
|===

| N°
| Nom
| Pouvoir

| 1
| L'Antre
a| Au choix :

- reprenez en main les cartes Lieu de votre défausse (mais pas celui-ci),
- copiez le pouvoir d'un Lieu où le jeton Créature se trouve,

Perdez 1 Volonté supplémentaire si le jeton Créature vous attrape.

| 2
| La Jungle
| Reprenez en main cette carte Lieu et 1 carte Lieu de votre défausse.

| 3
| La Rivière
| Au prochain tour, jouez 2 cartes Lieu.

Avant de révéler, choisissez-en une et reprenez l'autre en main.

| 4
| La Plage
a| Au choix, 1 fois par tour :

- placez le pion Balise sur la Plage,

- retirez le pion Balise de la Plage pour avancer le pion Secours d’une case (max 1x/tour).

Si plusieurs Traqués explorent la Plage, l’un d’eux peut utiliser le pouvoir de la Plage et les autres peuvent récupérer 1 carte Lieu de leur défausse.

Le pouvoir de la Plage est cumulable avec celui de l’Épave.

| 5
| Le Rover
| Prenez de la réserve une carte Lieu que vous ne possédez pas et ajoutez-le à votre main.


| 6
| Le Marais
a| Reprenez en main cette carte Lieu et 2 cartes Lieu de votre défausse.

.Précision:
- Si le Marais est révélé grâce au Labyrinthe et que vous l’activez directement, ni le Marais ni le Labyrinthe ne sont repris en main.

| 7
| L'Abri
| Piochez 2 carte Survie, gardez-en une et défaussez l'autre.

| 8
| L'Épave
| Avancez le pion Secours d'1 case (1 fois par tour, quel que soit le nombre de Traqués explorant l’Épave).

Si plusieurs Traqués explorent l’Épave, l’un d’eux peut utiliser le pouvoir de l’Épave et les autres peuvent récupérer 1 carte Lieu de leur défausse.

Le pouvoir de l’Épave est cumulable avec celui de la Plage.

| 9
| La Source
a| Au choix :

- le Traqué de votre choix (vous ou un autre joueur) récupère 1 Volonté,
- piochez 1 carte Survie.

| 10
| L'Artefact
a| Le pouvoir de l'Artefact varie selon la couleur choisie pour la partie.

L’Artefact ne peut être copié (que ce soit par le pouvoir d'un Lieu ou une carte Survie).

.Bleu
Au prochain tour, jouez 2 cartes Lieu.

Résolvez les deux Lieu individuellement dans l’ordre de votre choix en respectant les règles de la Phase 3.

Lorsqu’un Traqué révèle ses cartes Lieu, s’il peut appliquer les effets de la Rivière et de l’Artefact bleu durant
un même tour, il doit choisir l’un des deux effets, puis il peut reprendre une carte Lieu de sa défausse.

.Rouge
Copiez les effets d'1 carte Lieu de votre défausse.

.Vert
Défaussez 1 carte Lieu et déplacez 1 Traqué de votre choix sur un Lieu adjacent.

.Jaune
Au choix :

- annulez les effets du jeton Artemia,
- récupérez 2 cartes Lieu de votre défausse.

|===




== Cartes traque

Fonctionnement::
Chaque carte Traque possède un nom, une Phase où elle peut être joéue et un effet pouvant être activé par la Créature.
Certaines cartes Traque possèdent également le symbole Cible ou Artemia.
Une carte Traque se joue à tout moment de la phase indiquée sur la carte et est ensuite défaussée.

Précision::
Quand l'effet d'une carte Traque qui indique "Dès que les cartes Lieu sont révélées à la Phase 3" : il est appliqué dès que chaque Traqué a dévoilé sa carte Lieu, avant la résolution des cartes Lieu.

Symbole Cible::
Lorsqu'une carte Traque avec le symbole Cible est jouée, la Créature pose le jeton Cible sur une des dix cartes Lieu d'Artemia.
Si la Créature joue 2 cartes Traque avec ce symbole au cours d’un même tour, leurs effets sont cumulés sur le Lieu ciblé.

Symbole Artemia::
Lorsqu'une carte Traque avec le symbole Artemia est jouée, la Créature pose le jeton Artemia sur une des dix cartes Lieu d'Artemia.
Si la Créature joue 2 cartes Traque avec ce symbole au cours d’un même tour, leurs effets sont cumulés.

.Liste des cartes traque
[cols="30,10,60",options="header"]
|===
| Nom
| Phase
| Effet

| Acharnement
| 2
| Le jeton Créature fait perdre 1 Volonté supplémentaire.

| Angoisse
| 1 - Artémia
| Les traqués ne peuvent pas Résister.

| Anticipation
| 2
| Désigner 1 Traqué : si vous l’attrapez avec le jeton Créature, avancez le jeton Assimilation d’1 case supplémentaire.

| Cataclysme
| 3
| Le pouvoir du Lieu de votre choix est inutilisable.

| Champ de force
| 1 - Cible
| Avant que les Traqués ne jouent, ciblez 2 Lieux adjacents : ces Lieux sont inaccessibles pour ce tour.

| Clone
| 2 - Cible
| Considérez le jeton Cible comme un second jeton Créature.

| Déploiement
| 3
| Dès que les cartes Lieu sont révélées en Phase 3, reculer le pion Assimilation d'1 case
pour déplacer le jeton Créature sur un Lieu adjacent.

| Désespoir
| 1 - Artemia
| Aucune carte Survie ne peut être jouée ou piochée pour le reste du tour.

| Détour
| 3
| Avant de résoudre les Lieux, déplacer 1 Traqué vers 1 Lieu adjacent.

| Domination
| 2
|Poser cette carte devant 1 Traqué : à la fin de chaque tour, celui-ci doit défausser 1 carte Lieu de sa
main.

Si ce Traqué tombe à 0 Volonté, défausser cette carte.

| Effroi
| 1
| Obligez un Traqué qui utilise l'action Résister à Lâcher prise.

| Emprise
| 2
| Cibler 1 Traqué : il défausse toutes ses cartes Lieu sauf 2.

| Épidémie
| 2
a| Désignez 1 Traqué :

- le Lieu où il se trouve est inutilisable,
- chaque autre Traqué présent sur ce Lieu perd 1 Volonté.

| Faille temporelle
| 2 - Cible
| Pour chaque Traqué présent sur le Lieu ciblé, avancer le pion Assimilation d'autant de cases, puis le pion Secours d'autant de cases.

| Flashback
| Spécial
| À jouer à la phase de la carte copiée : copier la dernière carte Traque défaussée.

| Gargantua
| 2
| Placer le jeton Créature sur 2 Lieux adjacents : ses effets s'appliquent sur ces 2 Lieux.
Si un Traqué copie le pouvoir du Lieu où se trouve le jeton Créature, il copie 1 seul des 2 Lieux.

| Harcèlement
| 2
| Chaque Traqué ne peut récupérer qu'1 carte Lieu quand il utilise le pouvoir d'un Lieu.

| Hurlements
| 2 - Cible
| Chaque Traqué présent sur le Lieu ciblé doit, selon son choix, défausser 2 cartes Lieu ou perdre 1 Volonté.

| Inertie
| 2 - Cible
| Dès que les cartes Lieu sont révélées à la Phase 3, si au moins 1 Traqué se trouve sur le Lieu ciblé :
les pouvoirs de tous les Lieux sont inutilisables, les effets des jetons Créature et Artemia sont quand même résolus.

| Interférences
| 2
a| Au choix:

- les pouvoirs de la Plage et de l’Épave sont inutilisables,
- reculer le pion Bouclier d'1 Lieu.

| Intuition
| 1
a|
. Piocher 3 cartes Traque,
. Jouer 1 de ces cartes durant le tour et défausser les 2 autres.

| Magnétisme
| 2 - Cible
| Dès que les cartes Lieu sont révélées en Phase 3, chaque Traqué adjacent au Lieu ciblé est déplacé sur le Lieu ciblé.

| Mirage
| 2 - Cible
| Ciblez 2 Lieux adjacents (placer le jeton Cible entre ces 2 Lieux) : leur pouvoir est inutilisable.

| Mutation
| 2 - Artemia
| En plus de ses effets, le jeton Artemia fait perdre 1 Volonté.

| Psychose
| 2 - Artemia
| Désigner 1 Traqué : il vous montre toutes les cartes Lieu de sa main sauf 2.

| Réminiscence
| 2 - Artemia
| Reprendre 1 carte Traque de la défausse.

| Repérage
| 4
| Au prochain tour, vous pouvez jouer jusqu’à 2 cartes Traque.

| Sables mouvants
| 2 - Cible
| Chaque Traqué présent sur le Lieu ciblé choisit et défausse toutes les cartes Lieu de sa main sauf 2.

| Soif de sang
| 2 - Cible
a|
. Chaque Traqué présent sur le Lieu ciblé récupère 1 Volonté, si possible,
. Chaque Traqué présent sur un Lieu adjacent au Lieu ciblé perd 1 Volonté.

| Stase
| 4
| Le pion Secours n'avance pas lors de cette Phase.

| Télépathie
| 2 - Artemia
a|
. Désigner 1 Lieu,
. Choisir 1 Traqué, tirer au hasard 1 carte de sa main et la défausser,
. Si la carte correspond au Lieu désigné : avancer le pion Assimilation d'1 case.

| Tornade
| 2 - Artemia
| Dès que les cartes Lieu sont révélées à la Phase 3, vous pouvez déplacer le jeton Artemia sur un Lieu adjacent.

| Toxine
| 2 - Cible
| Chaque Traqué sur le Lieu ciblé défausse 1 carte Survie.

Le pouvoir de ce lieu est inutilisable.

| Ubiquité
| 2 - Artemia + Cible
| Dès que les cartes Lieu sont révélées à la Phase 3, vous pouvez permuter les jetons Traque.

Si un jeton Traque se trouve sur 2 Lieux adjacents, le jeton qui le remplace est placé sur ces 2 Lieux adjacents.

| Virus
| 2 - Artemia
| Ciblez 2 Lieux adjacents : les effets du jeton Artemia s'appliquent sur ces 2 Lieux.

| Zone interdite
| 2
| Tous les Traqués défaussent simultanément 1 carte Lieu de leur choix.

|===

== Cartes survie

Fonctionnement::
Chaque carte Survie possède un nom, une Phase où elle peut être joéue et un effet pouvant être activé par le Traqué qui la détient.
Une carte Survie se joue à tout moment de la phase indiquée sur la carte et est ensuite défaussée.

.Liste des cartes survie
[cols="30,10,60"]
|===
| Nom | Phase | Effet

| Adrénaline
| 1
| Récupérez 1 Volonté.

| Alerte
| 3
a| Désigner 1 Lieu :

- les jetons Traque présents sur ce Lieu sont sans effet,
- le pouvoir de ce Lieu est inutilisable.

| Amplificateur
| 4
a| Au choix:

- retirez le jeton Balise de la Plage pour avancer le pion Secours d’1 case,
- avancez le pion Bouclier d'1 Lieu vers le Dôme.

| Brouillage
| 1
| Tous les Traqués cachent les cartes Lieu de leur défausse jusqu’à la fin du tour

| Cavale
| 1
a|
. Jouez 3 cartes Lieu,
. En Phase 3 : révélez celle de votre choix,
. En Phase 4 : reprenez en main la carte révélée et défaussez les 2 autres.

| Détecteur
| 3
| Évitez les effets du jeton Artemia.

| Drone
| 3
| À la place d'utiliser le pouvoir de votre carte Lieu,
prenez de la réserve 1 carte d'un Lieu révélé que vous ne possédez pas et
ajoutez-la à votre main.

| Entrave
| 1
| Le jeton Créature ne peut pas être posé sur les Lieux 6 à 10.

| Équipement
| 4
a| Au choix :

- piochez 1 carte Survie,
- prenez la carte Survie du dessus de la défausse.

| Esquive
| 3
| Évitez les effets du jeton Créature.

| Fausse piste
| 3
| Déplacez le jeton Créature sur un Lieu adjacent.

| Hologramme
| 3
| Déplacez le jeton Artemia sur un Lieu adjacent.

| Leurre
| 3
a|
. Permutez 2 jetons Traque,
. Reprenez 1 carte Lieu de votre défausse.

| Mimétisme
| 1
| En Phase 3, si vous êtes sur le même Lieu que le jeton Créature : avancez le pion Secours d'1 case,
vous ne subissez pas les effets du jeton Créature.

| Navette
| 4
| Jouer cette carte quand le pion Secours se trouve à 1 case de la case Victoire :
les Traqués reportent la partie.

| Planques
| 4
| Piocher 2 cartes Survie et les placer face cachée chacune sous 1 Lieu d'Artemia :
si un Traqué explore un de ces Lieux et peut utiliser son pouvoir,
il peut également récupérer la carte Survie qui s'y trouve.

| Portail
| 3
| À la place d'utiliser le pouvoir de votre carte Lieu, copiez le pouvoir d’1
Lieu adjacent.

| Ralliement
| 4
| Chaque Traqué attrapé par le jeton Créature peut reprendre en main la carte Lieu sur laquelle il s'est fait attraper.

| Refuge
| 1
| Poser le jeton Cible sur 2 Lieux adjacents : le jeton Créature ne peut être posé sur
ces Lieux Aucune carte Traque avec le symbole Cible ne peut être jouée.

| Régénération
| 3
| À la place d'utiliser le pouvoir de votre carte Lieu,
copiez le pouvoir d’1 carte Lieu de votre défausse.

| Résistance
| 3
| Évitez les effets du jeton Cible.

| Retraite
| 3
| Déplacez 1 Traqué de votre choix sur un Lieu adjacent, le Lieu de destination n'est pas résolu.

| Riposte
| 1
| Tirer 2 cartes Traque au hasard de la main de la Créature et placez-lez sous la pioche Traque.

| Sacrifice
| 1
| Défaussez 1 carte Lieu : aucune carte Traque ne peut être jouée ce tour-ci.

| Second souffle
| 1
| Si vous avez au plus 1 carte Lieu en main : récupérez toutes les cartes Lieu de votre défausse.

| Sixième sens
| 1
| Reprenez en main 2 carte Lieu de votre défausse.

| Système D
| 1
a| Au choix:

- placez le pion Balise sur la Plage,
- avancez le pion Bouclier d'1 Lieu vers le Dôme.

| Ténacité
| 1
| Récupérez 1 carte Lieu supplémentaire pour chaque Volonté dépensée dans l'action Résister.

| Vaccin
| 1
| Reculer le pion Assimilation d'1 case.

| Volte-face
| 4
| Reprenez en main votre carte Lieu jouée.

| Vortex
| 2
| Échangez votre carte Lieu jouée contre 1 carte Lieu de votre défausse.

|===

== Mise en place

.Nombre cartes lieu
[cols="60h,10,10,10"]
|===
| Nombre de Traqués | 1 | 2-3 | 4-6
| Nombre de Cartes Lieu 6 à 10 | 1 | 2 | 3
|===

.Mise en place
[cols="30h,40"]
|===
| Action | Description

| Choix
a|
. Choisir un mode de difficulté : normal ou expert.
. Choisir si l'extension Exploration est utilisée.
. Choisir si la variante Labyrinthe est utilisée (l'extension Exploration est obligatoire dans ce cas).
. Choisir quel joueur incarne la Créature, les autres joueurs étant les Traqués.

| Créer la planète Artemia
a|
. Placer 1 exemplaire des 10 cartes Lieu devant la créature en 2 rangées de chacune 5 cartes, par ordre croissant,
. Placer le pion Balise à côté de la carte Plage.

| Pioche Traque
| Mélanger et placer face cachée les cartes Traque à proximité de la Créature.

| Pioche Survie
| Mélanger et placer face cachée les cartes Survie à proximité des Traqués.

| La Créature:
a|
- place le plateau au centre de la table sur la face de son choix,
- place le pion Secours et le pion Assimilation sur le chiffre de leur piste respective correspondant au nombre de joueurs,
- pioche 3 cartes Traque et prend les 3 jetons Traque (Créature, Cible et Artemia).

| Chaque Traqué:
a|
- prend 3 pions Volonté, les pions Volonté restants sont retirés du jeu,
- prend un set de 5 cartes Lieu numérotées de 1 à 5, les cartes inutilisées sont retirées du jeu,
- pioche 1 carte Survie.

| Réserve
| Former la réserve Lieux avec les cartes Lieu numérotées de 6 à 10.

Placer près du plateau le nombre d’exemplaires de chaque carte Lieu correspondant au nombre de Traqués (voir le tableau "Traqués"), face visible, les cartes inutilisées sont retirées du jeu.

|===

== Conditions de victoire

La Créature remporte immédiatement la partie si le pion Assimilation atteint la case Victoire.

Les Traqués remportent immédiatement la partie si le pion Secours atteint la case Victoire.

== Déroulement d'une partie

.Règles générales
[cols="30h,70"]
|===
| Fonctionnement
| La partie est une succession de tours de jeu.

| Règle d'or
| Tout effet ou pouvoir qui contredit la règle prévaut sur elle.

| Informations
| Les cartes Lieu défaussées par les Traqués sont visibles de tous.

Le nombre de cartes en possession de chacun et leur type (leur dos) est connu de tous, mais il est interdit de montrer ses cartes aux autres joueurs.

Les Traqués peuvent communiquer et bluffer, mais uniquement à voix haute.

| Cartes en main
| Le nombre de cartes Survie qu’un Traqué peut détenir n’est pas limité.

| Durée des effets
| Les effets des cartes Traque et des cartes Survie sont limités au tour de jeu en cours.

Les effets d'une carte Survie ciblent uniquement leur propriétaire, sauf indication contraire.

| Ordre de résolution des cartes
| Les effets des cartes Traque et des cartes Survie jouées lors d’une même phase sont résolus dans l’ordre dans lequel les cartes ont été jouées.

En cas de conflit, la Créature décide de l’ordre de résolution.

| Pions Volonté
| Un Traqué ne peut jamais avoir plus de 3 pions Volonté en sa possession.

Tout effet qui ferait perdre plus que les pions Volonté restants à un Traqué se limite à lui faire perdre les pions Volonté restants.

| Pioche Survie
| Si, au moment de piocher, la pile des cartes Survie est vide :
mélanger les cartes Survie défaussées pour former une nouvelle pioche.

|===

.Tour de jeu
[cols="30h,70"]
|===
| Fonctionnement
| Résoudre les Phases suivantes dans l'ordre.

| Créature
| Par défaut, la Créature ne peut jouer qu’1 carte Traque par tour.

| Traqués
| Chaque Traqué ne peut jouer qu’1 carte Survie par tour, et ce, même s’il est attrapé par la Créature.

| Phase 1 : Exploration
| Les Traqués jouent simultanément et obligatoirement 1 carte Lieu de leur main en la posant face cachée devant eux.

| Actions optionnelles
| Avant de jouer une carte Lieu, chaque Traqué peut Résister ou Lâcher prise.

| Résister
a| Lorsqu'un Traqué Résiste, il choisit 1 des cas suivants :

- perdre 1 pion Volonté pour choisir et reprendre en main 2 cartes Lieu de sa défausse,
- perdre 2 pions Volonté pour choisir et reprendre en main 4 cartes Lieu de sa défausse.

Si par cette action un Traqué perd son dernier pion Volonté, il doit résoudre Lâcher prise.

| Lâcher prise
a|
. Récupérer ses 3 pions Volonté et reprendre en main toutes ses cartes Lieu défaussées,
. Avancer le pion Assimilation d'1 case.

| Phase 2 : Traque
a| La Créature pose sur les cartes Lieu d'Artemia de son choix :

- le jeton Créature,
- le jeton Cible si le symbole se trouve sur une carte Traque jouée,
- le jeton Artemia si le symbole se trouve sur une carte Traque jouée ou sur une case située sous le pion Secours.

| Précision
| Plusieurs jetons Traque peuvent être posés sur un même Lieu pour en cumuler leurs effets.

| Phase 3 : Résolution
| Résoudre les étapes suivantes dans l'ordre :

| 1) Choix des Traqués
| Les Traqués qui ont le choix parmi plusieurs cartes Lieu décident secrètement du Lieu qu’ils vont explorer.

| 2) Révélation
| Les Traqués dévoilent simultanément leur carte Lieu.

| 3) Lieux sans jeton Traque
a| Résoudre les Lieux sans jeton Traque, en sens horaire depuis le joueur à gauche de la Créature. Le Traqué peut au choix, si le Lieu n'est pas inutilisable :

- utiliser le pouvoir du Lieu,
- reprendre en main 1 carte Lieu au choix de sa défausse.

| 4) Lieu avec jeton Cible
a| Résoudre le Lieu avec le jeton Cible, en sens horaire depuis le joueur à gauche de la Créature :

A) Chaque Traqué présent sur ce Lieu subit l’effet de la carte Traque,

B) Chaque Traqué présent sur ce Lieu peut au choix, si le Lieu n'est pas inutilisable :

- utiliser le pouvoir du Lieu,
- reprendre en main 1 carte Lieu au choix de sa défausse.

| 5) Lieu avec jeton Artemia
a| Résoudre le Lieu avec le jeton Artemia, en sens horaire depuis le joueur à gauche de la Créature :

A) Chaque Traqué présent sur ce Lieu choisit et défausse 1 carte Lieu de sa main,

B) Le pouvoir du Lieu est inutilisable et le Traqué ne peut pas reprendre de carte Lieu de sa défausse.

| 6) Lieu avec jeton Créature
a| Résoudre le Lieu avec le jeton Créature, en sens horaire depuis le joueur à gauche de la Créature :

A) Le pouvoir du Lieu est inutilisable et le Traqué ne peut pas reprendre de carte Lieu de sa défausse,

B) Avancer immédiatement le pion Assimilation d'1 case,

C) Chaque Traqué présent sur ce Lieu est attrapé par la Créature et perd 1 pion Volonté,

D) Si au moins 1 Traqué perd son dernier pion Volonté : avancer le pion Assimilation d'1 case.

| 7) Récupération
a| Pour chaque Traqué ayant perdu ses 3 pions Volonté, en fonction du mode de difficulté.

Mode normal:: Il reprend en main toutes les cartes Lieu de sa défausse ainsi que ses 3 pions Volonté.

Mode expert:: Il reprend en main toutes les cartes Lieu de sa défausse ainsi que 2 pions Volonté (le pion restant peut être récupéré par tout autre moyen).

| Phase 4 : Maintenance
a|
A) Chaque Traqué défausse sa carte Lieu jouée, face visible de façon à ce que le n° de chacune de ses cartes Lieu défaussées soit visible,

B) La Créature reprend ses jetons Traque et pioche des cartes Traque jusqu’à en avoir 3 en main,

C) Avancer le pion Secours d'1 case, un nouveau tour de jeu commence.
|===

== Extension Exploration

.Liste des cartes lieu (exploration)
[cols="10,20,70"]
|===
| N° | Nom | Effet

| 1
| Le Nexus
a|
. Copiez le pouvoir d'1 Lieu 2à 5.
. Avancez le pion Assimilation d'1 case supplémentaire si le jeton Créature attrape au moins 1 Traqué sur le Nexus.

| 2
| L'Oasis
| Reprenez en main cette carte Lieu plus 1 carte Lieu de votre défausse par Volonté qu'il vous manque, si possible.

| 3
| Le Fjord
a| Lors du prochain tour :

. En Phase 1 : vous pouvez jouer une 2ème carte Lieu, face visible, de votre défausse, s'il n'y en a,
. En Phase 3 : résolvez 1 de ces Lieux,
. En Phase 4 : défaussez ces 2 cartes Lieu.

| 4
| Le Dôme
a|
. Déplacez le Bouclier d'1 Lieu vers le Dôme.
. Si le pion Boucler atteint le Dôme : reculer le pion Assimilation d'1 case et replacer le pion Bouclier sur le Lieu 1 (max 1x/tour).

| 5
| Le Labyrinthe
a| Au choix :

- révéler un Lieu : retourner, face visible, une des 5 cartes Lieu 6 à 10 de la planète Artemia et activer son pouvoir ou prendre 1 carte Lieu correspondante,
- prendre de la réserve 1 carte Lieu déjà révélé.

| 6
| La Mangrove
a|
. Échanger les cartes Lieu de sa main contre celles de sa défausse,
. Reprendre cette carte Lieu en main.

Précision:: Si la Mangrove est révélée grâce au Labyrinthe et que vous l’activez directement,
ni la Mangrove ni le Labyrinthe ne sont repris en main.

| 7
| L'Archipel
a|
. Piocher 1 carte Survie,
. S'il vous reste moins de 3 cartes Lieu en main, le Traqué de votre choix récupère 1 Volonté.

| 8
| Le Pôle
a|
. Sacrifiez 1 Volonté (même si c'est le dernier), puis avancez le pion Secours de 2 cases,
. En Phase 4, replacer le pôle dans la réserve, qu’elle ait pu être activée ou non,

Le Pôle ne peut être copié (que ce soit par le pouvoir d'un Lieu ou une carte Survie).

| 9
| Les Fungi
a| Au choix :

- piocher 1 carte Survie,
- placer jusqu’à 2 pions Volonté (si possible) sur des cases libres différentes de la piste Secours, ce pouvoir est inutilisable si la réserve de pions Volonté est vide ou s’il n’y a plus de case libre pour placer un pion Volonté. Quand le pion Secours atteint une de ces cases : les Traqués décident ensemble qui récupère le pion Volonté. Si un Traqué doit récupérer au moins 1 Volonté alors que la réserve est vide, il prend les pions Volonté disponibles de son choix sur la piste Secours.

| 10
| Le Portail
a|
. Défausser le Portail pour jouer une autre carte Lieu de sa main et la résoudre.
Le Portail téléporte le Traqué sur le second lieu joué, ce Traqué est donc susceptible de s’y faire attraper par un jeton Traque et/ou d’y être la cible d’une carte Traque,
. Le Portail est défaussé en phase 3 et la seconde carte Lieu en phase 4.
|===

