@startuml

actor Créature
participant ClientWeb1
database Server
participant ClientWeb2
actor Traqué

Créature -> Server : idGame := CreateGame(6)
Créature -> Server : playerId := join(id, one)
Traqué -> Server : playerId := join(id, creature)

Server -> Server : recherchePartie()
Server -> Server : creerPartie(List<Joueur>)
Server -> Créature : getIdPartie(partie)
Traqué -> Server : joindre(idPartie)
Server -> Traqué : getIdPartie(partie)
Créature -> Créature : initPartie()
Traqué -> Server : initPartie()
Server -> Créature : donnerTour(joueur)
Créature -> Créature : jouerTour()
Créature -> Server : miseAjour(List<Joueur>)
Server -> Server : stockageInfos()
Server -> Server : getGagnant()
Server -> Traqué : effetCreature()
Server -> Traqué : donnerTour(Joueur)
Traqué -> Traqué : jouerTour()
Traqué -> Server : miseAjour(List<Joueur>)
Server -> Server : stockageInfos()
Server -> Server : getGagnant()



@enduml
