= Conception préliminaire

== Création d'une partie

.Join game
[plantuml]
....
participant "__one:Player__" as player1
participant "__two:Player__" as player2
participant "__three:Player__" as player3
participant "__four:Player__" as player4
participant "__five:Player__" as player5
participant "__six:Player__" as player6
participant "__game:GameServer__" as game

player1 -> game : id := createGame(6)
par
    player1 -> game : playerId := join(id, one)
    player2 -> game : playerId := join(id, two)
    player3 -> game : playerId := join(id, three)
    player4 -> game : playerId := join(id, four)
    player5 -> game : playerId := join(id, five)
    player6 -> game : playerId := join(id, six)
end
....

- Les joeurs ne peuvent pas envcoyer juste une `id`, ils doivent aussi envoyer une adress/port pour que le serveur puisse les contacter
- Le serveur doit prévenir les joueurs du début de la partie.

.L'interface GameServer
[plantuml]
....
interface GameServer {
    createGame(numberOfPlayers : Integer): Integer
    join(gameId : Integer): Integer
}
....

[planuml]

== Création d'une  nouvelle partie

[plantuml]
....
participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

player1 -> game : id := createGame(6)
par
player1 -> game : playerId := join(id, one, port)
player2 -> game : id := join(id, two)
end
....

== Joindre une partie existante

[plantuml]
....
participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

player1 -> game : id := searchGame()
par
player1 -> game : playerId := join(id, one, port)
player2 -> game : id := join(id, two)
end
....

== Commencer la partie
[plantuml]
....

participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

game -> player1 : beginGame()
game ->  player2 : beginGame()
player1 -> player1 :  initCards()
player2 -> player2 : initCards()

....



== Jouer tour

[plantuml]
....

participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

game -> player1 : giveTurn(id_joueur )
player1 -> player1 : play()
player1 -> game : update(id_joueur, instanceGame)
game -> player2 : giveTurn(id_joueur)
player2 -> player2 : play()
player2 -> game : update(id_joueur, instanceGame)

....

== Fin du jeu

[plantuml]
....

participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

game -> game : id_Gangant := getWinner()
game -> player1 : id_Gangant := gameOver(id_Gagnant)
game -> player2 : id_Gangant := gameOver(id_Gagnant)
....


[planuml]
