= Conception préliminaire

== Création d'une  nouvelle partie

[plantuml]
....
participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

player1 -> game : id := createGame(6)
par
player1 -> game : playerId := join(id, one, port)
player2 -> game : id := join(id, two)
end
....

== Joindre une partie existante

[plantuml]
....
participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

player1 -> game : id := searchGame()
par
player1 -> game : playerId := join(id, one, port)
player2 -> game : id := join(id, two)
end
....

== Commencer la partie
[plantuml]
....

participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

game -> player1 : beginGame()
game ->  player2 : beginGame()
player1 -> player1 :  initCards()
player2 -> player2 : initCards()

....



== Jouer tour

[plantuml]
....

participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

game -> player1 : giveTurn(id_joueur )
player1 -> player1 : play()
player1 -> game : update(id_joueur, instanceGame)
game -> player2 : giveTurn(id_joueur)
player2 -> player2 : play()
player2 -> game : update(id_joueur, instanceGame)

....

== Fin du jeu

[plantuml]
....

participant "__one:Traqué__" as player1
participant "__two:Créature__" as player2
participant "__game:GameServer__" as game

game -> game : id_Gangant := getWinner()
game -> player1 : id_Gangant := gameOver(id_Gagnant)
game -> player2 : id_Gangant := gameOver(id_Gagnant)
....

